# Metadata for your course

title: Write a Learning Lab course
tagline: Write a Learning Lab course
description: Write a Learning Lab course
template:
  name: lab-starter
  repo: write-a-ll-course-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
  - type: createIssue
    title: Welcome
    body: welcome.md
    data:
      prUrl: '%payload.repository.html_url%/compare/master...add-metadata?expand=1'
# Steps for the course
# A list of steps that take the learner through the course

steps:

# 1
- title: Open a PR to begin crafting your course
  description: Open a PR to begin crafting your course
  event: pull_request.opened
  actions:
  - type: respond
    with: add-title.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      title: An amazing course by %payload.sender.login%.
      ```
    position: 6

# 2
- title: Give your course a title
  description: Give your course a title
  event: pull_request.synchronize
  actions: 
  - type: respond
    with: add-template.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        repo: lab-starter-template
      ```
    position: 13

# 3. Point to the template repo
# 4. Give the learner's repo a name
# 5. Create an issue using Learning Lab
# 6. Create your first response
# 7. Name your first step and give it a description
# 8. Trigger your first step with a GitHub event
# 9. Respond to a learner's pull request
# 10. Validate a learner's pull request
# 11. Pass contextual information to a response
# 12. Add some descriptions to your course
# 13. Add a README to your course
# 14. Deploy your course to the sandbox