# Metadata for your course

title: Write a Learning Lab course
tagline: Write a Learning Lab course
description: Write a Learning Lab course
template:
  name: lab-starter
  repo: write-a-ll-course-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
  - type: createIssue
    title: Welcome
    body: welcome.md
    data:
      prUrl: '%payload.repository.html_url%/compare/master...add-metadata?expand=1'
# Steps for the course
# A list of steps that take the learner through the course

steps:

# 1
- title: Open a PR to begin crafting your course
  description: Open a PR to begin crafting your course
  event: pull_request.opened
  actions:
  - type: respond
    with: add-title.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      title: An amazing course by %payload.sender.login%.
      ```
    position: 6

# 2
- title: Give your course a title
  description: Give your course a title
  event: pull_request.synchronize
  actions: 
  - type: respond
    with: add-template.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        repo: lab-starter-template
      ```
    position: 13

# 3
- title: Point to the template repo
  description: Point to the template repo
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-repo-name.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        name: my-sparkles-repo
      ```
    position: 12

# 4
- title: Give the learner's repo a name
  description: Give the learner's repo a name
  event: pull_request.synchronize
  actions:
  - type: respond
    with: create-issue.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      - type: createIssue
      ```
    position: 22
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        title: Welcome
      ```
    position: 23
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        body: welcome-text.md
      ```
    position: 24

# 5
- title: Create an issue using Learning Lab
  description: Create an issue using Learning Lab
  event: pull_request.synchronize
  actions: 
  - type: respond
    with: add-response.md

# 6
- title: Create your first response
  description: Create your first response
  event: pull_request.synchronize
  actions:
  - type: getTree
    action_id: tree
    recursive: true
    sha: '%payload.pull_request.head.sha%'
  - type: gate
    left: '%actions.tree.data.tree%'
    operator: includes
    right: path:responses/welcome-text.md
    else:
      type: respond
      with: e-no-response.md
  - type: respond
    with: add-first-step.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
      - title: Create a new PR
      ```
    position: 33
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        description: Add your name to the README.md file in your new PR
      ```
    position: 34

# 7
- title: Name your first step and give it a description
  description: Name your first step and give it a description
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-trigger.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        event: pull_request.opened
      ```
    position: 35

# 8
- title: Trigger your first step with a GitHub event
  description: Trigger your first step with a GitHub event
  event: pull_request.synchronize
  actions:
  - type: respond
    with: validate.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        - type: gate
      ```
    position: 35

# 9
- title: Validate a learner's PR
  description: Validate a learner's PR
  event: pull_request.synchronize
  actions:
  - type: respond
    with: add-context.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          left: '%payload.pull_request.title%'
      ```
    position: 41
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          operator: ===
      ```
    position: 42
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          right: Add name to README
      ```
    position: 43

# 10
- title: Pass contextual information to a response
  description: Pass contextual information to a response
  event: pull_request.synchronize
  actions:
  - type: respond
    with: respond-to-pr.md
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
        - type: respond
      ```
    position: 45
  - type: octokit
    method: pullRequests.createComment
    owner: '%payload.repository.owner.login%'
    repo: '%payload.repository.name%'
    number: '%payload.number%'
    commit_id: '%payload.pull_request.head.sha%'
    path: config.yml
    body: |
      ```suggestion
          with: pr-opened.md
      ```
    position: 46

# 10
# - title: Respond to a learner's PR
#   description: Respond to a learner's PR
#   event: pull_request.synchronize
#   actions:


# 12. Add some descriptions to your course
# 13. Add a README to your course
# 14. Deploy your course to the sandbox